// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OqYTFuB8HWXjn2C5iYAOg-mZLQUs4p8',
    appId: '1:119993363465:web:c408e56f9d862accb79cd8',
    messagingSenderId: '119993363465',
    projectId: 'smart-944cb',
    authDomain: 'smart-944cb.firebaseapp.com',
    storageBucket: 'smart-944cb.firebasestorage.app',
    measurementId: 'G-MV21Y8SPM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTUrYm7Og_Lm986Jfu_ahM_M76XPLLE9E',
    appId: '1:119993363465:android:bdd84d07f77f1c26b79cd8',
    messagingSenderId: '119993363465',
    projectId: 'smart-944cb',
    storageBucket: 'smart-944cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9i0VU5yAZcC4EhvEpHkCNVCCrEayfP0',
    appId: '1:119993363465:ios:007cdfe590753fd6b79cd8',
    messagingSenderId: '119993363465',
    projectId: 'smart-944cb',
    storageBucket: 'smart-944cb.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo9i0VU5yAZcC4EhvEpHkCNVCCrEayfP0',
    appId: '1:119993363465:ios:007cdfe590753fd6b79cd8',
    messagingSenderId: '119993363465',
    projectId: 'smart-944cb',
    storageBucket: 'smart-944cb.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_OqYTFuB8HWXjn2C5iYAOg-mZLQUs4p8',
    appId: '1:119993363465:web:87bfb12188d12d0db79cd8',
    messagingSenderId: '119993363465',
    projectId: 'smart-944cb',
    authDomain: 'smart-944cb.firebaseapp.com',
    storageBucket: 'smart-944cb.firebasestorage.app',
    measurementId: 'G-X6ZV60DQ0L',
  );
}
